package it.eng.parer.grantedEntity;

import java.io.Serializable;
import java.util.List;
import javax.persistence.*;

/**
 * Auto-generated by: org.apache.openjpa.jdbc.meta.ReverseMappingTool$AnnotatedCodeGenerator edited by fioravanti_f
 */
@Entity
@Table(schema = "SACER_IAM", name = "APL_TIPO_ORGANIZ")
public class SIAplTipoOrganiz implements Serializable {

    private SIAplApplic sIAplApplic;
    private String flLastLivello;
    private long idTipoOrganiz;
    private String nmTipoOrganiz;
    private List<SIUsrOrganizIam> usrOrganizIams;

    public SIAplTipoOrganiz() {
    }

    public SIAplTipoOrganiz(long idTipoOrganiz) {
        this.idTipoOrganiz = idTipoOrganiz;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "ID_APPLIC")
    public SIAplApplic getsIAplApplic() {
        return sIAplApplic;
    }

    public void setsIAplApplic(SIAplApplic sIAplApplic) {
        this.sIAplApplic = sIAplApplic;
    }

    @Basic
    @Column(name = "FL_LAST_LIVELLO", nullable = false, length = 1)
    public String getFlLastLivello() {
        return flLastLivello;
    }

    public void setFlLastLivello(String flLastLivello) {
        this.flLastLivello = flLastLivello;
    }

    @Id
    @Column(name = "ID_TIPO_ORGANIZ")
    public long getIdTipoOrganiz() {
        return idTipoOrganiz;
    }

    public void setIdTipoOrganiz(long idTipoOrganiz) {
        this.idTipoOrganiz = idTipoOrganiz;
    }

    @Basic
    @Column(name = "NM_TIPO_ORGANIZ", nullable = false, length = 100)
    public String getNmTipoOrganiz() {
        return nmTipoOrganiz;
    }

    public void setNmTipoOrganiz(String nmTipoOrganiz) {
        this.nmTipoOrganiz = nmTipoOrganiz;
    }

    @OneToMany(mappedBy = "siAplTipoOrganiz", cascade = CascadeType.MERGE)
    public List<SIUsrOrganizIam> getUsrOrganizIams() {
        return usrOrganizIams;
    }

    public void setUsrOrganizIams(List<SIUsrOrganizIam> usrOrganizIams) {
        this.usrOrganizIams = usrOrganizIams;
    }
}
