package it.eng.parer.grantedEntity;

import java.io.Serializable;
import javax.persistence.*;

/**
 * Auto-generated by: org.apache.openjpa.jdbc.meta.ReverseMappingTool$AnnotatedCodeGenerator edited by fioravanti_f
 */
@Entity
@Table(schema = "SACER_IAM", name = "DEC_USO_MODELLO_COMUNIC")
public class SIDecUsoModelloComunic implements Serializable {
    private SIDecModelloComunic siDecModelloComunic;
    private long idUsoModelloComunic;
    private SIOrgAmbienteEnteConvenz siOrgAmbienteEnteConvenz;
    private SIOrgEnteSiam siOrgEnteConvenz;
    private double pgUso;
    private String tipoUso;

    public SIDecUsoModelloComunic() {
    }

    public SIDecUsoModelloComunic(long idUsoModelloComunic) {
        this.idUsoModelloComunic = idUsoModelloComunic;
    }

    @ManyToOne(fetch = FetchType.LAZY, cascade = CascadeType.MERGE)
    @JoinColumn(name = "ID_MODELLO_COMUNIC", nullable = false)
    public SIDecModelloComunic getSiDecModelloComunic() {
        return siDecModelloComunic;
    }

    public void setSiDecModelloComunic(SIDecModelloComunic siDecModelloComunic) {
        this.siDecModelloComunic = siDecModelloComunic;
    }

    @Id
    @Column(name = "ID_USO_MODELLO_COMUNIC")
    public long getIdUsoModelloComunic() {
        return idUsoModelloComunic;
    }

    public void setIdUsoModelloComunic(long idUsoModelloComunic) {
        this.idUsoModelloComunic = idUsoModelloComunic;
    }

    @ManyToOne(fetch = FetchType.LAZY, cascade = CascadeType.MERGE)
    @JoinColumn(name = "ID_AMBIENTE_ENTE_CONVENZ")
    public SIOrgAmbienteEnteConvenz getSiOrgAmbienteEnteConvenz() {
        return siOrgAmbienteEnteConvenz;
    }

    public void setSiOrgAmbienteEnteConvenz(SIOrgAmbienteEnteConvenz siOrgAmbienteEnteConvenz) {
        this.siOrgAmbienteEnteConvenz = siOrgAmbienteEnteConvenz;
    }

    @ManyToOne(fetch = FetchType.LAZY, cascade = CascadeType.MERGE)
    @JoinColumn(name = "ID_ENTE_CONVENZ")
    public SIOrgEnteSiam getSiOrgEnteConvenz() {
        return siOrgEnteConvenz;
    }

    public void setSiOrgEnteConvenz(SIOrgEnteSiam siOrgEnteConvenz) {
        this.siOrgEnteConvenz = siOrgEnteConvenz;
    }

    @Basic
    @Column(name = "PG_USO")
    public double getPgUso() {
        return pgUso;
    }

    public void setPgUso(double pgUso) {
        this.pgUso = pgUso;
    }

    @Basic
    @Column(name = "TIPO_USO", nullable = false, length = 30)
    public String getTipoUso() {
        return tipoUso;
    }

    public void setTipoUso(String tipoUso) {
        this.tipoUso = tipoUso;
    }
}