package it.eng.parer.grantedEntity;

import java.io.Serializable;
import javax.persistence.*;

/**
 * Auto-generated by: org.apache.openjpa.jdbc.meta.ReverseMappingTool$AnnotatedCodeGenerator edited by fioravanti_f
 */
@Entity
@Table(schema = "SACER_IAM", name = "DEC_COL_QUERY_MODELLO_COMUNIC")
public class SIDecColQueryModelloComunic implements Serializable {
    private SIDecQueryModelloComunic siDecQueryModelloComunic;
    private long idColQueryModelloComunic;
    private String nmCol;
    private long pgPosizCol;

    public SIDecColQueryModelloComunic() {
    }

    public SIDecColQueryModelloComunic(long idColQueryModelloComunic) {
        this.idColQueryModelloComunic = idColQueryModelloComunic;
    }

    @ManyToOne(fetch = FetchType.LAZY, cascade = CascadeType.MERGE)
    @JoinColumn(name = "ID_QUERY_MODELLO_COMUNIC", nullable = false)
    public SIDecQueryModelloComunic getSiDecQueryModelloComunic() {
        return siDecQueryModelloComunic;
    }

    public void setSiDecQueryModelloComunic(SIDecQueryModelloComunic siDecQueryModelloComunic) {
        this.siDecQueryModelloComunic = siDecQueryModelloComunic;
    }

    @Id
    @Column(name = "ID_COL_QUERY_MODELLO_COMUNIC")
    public long getIdColQueryModelloComunic() {
        return idColQueryModelloComunic;
    }

    public void setIdColQueryModelloComunic(long idColQueryModelloComunic) {
        this.idColQueryModelloComunic = idColQueryModelloComunic;
    }

    @Basic
    @Column(name = "NM_COL", nullable = false, length = 100)
    public String getNmCol() {
        return nmCol;
    }

    public void setNmCol(String nmCol) {
        this.nmCol = nmCol;
    }

    @Basic
    @Column(name = "PG_POSIZ_COL")
    public long getPgPosizCol() {
        return pgPosizCol;
    }

    public void setPgPosizCol(long pgPosizCol) {
        this.pgPosizCol = pgPosizCol;
    }
}
