package it.eng.parer.grantedEntity;

import java.io.Serializable;
import java.util.Date;

import javax.persistence.Basic;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;
import org.hibernate.id.enhanced.SequenceStyleGenerator;

/**
 * Auto-generated by: org.apache.openjpa.jdbc.meta.ReverseMappingTool$AnnotatedCodeGenerator edited by fioravanti_f
 */
@Entity
@Table(schema = "SACER_IAM", name = "ORG_ENTE_CONVENZ_ORG")
public class SIOrgEnteConvenzOrg implements Serializable {

    private Date dtFineVal;

    private Date dtIniVal;

    private Long idEnteConvenzOrg;

    private SIOrgEnteSiam siOrgEnteConvenz;

    private SIUsrOrganizIam siUsrOrganizIam;

    public SIOrgEnteConvenzOrg() {/* Hibernate */
    }

    public SIOrgEnteConvenzOrg(Long idEnteConvenzOrg) {
        this.idEnteConvenzOrg = idEnteConvenzOrg;
    }

    @Basic
    @Column(name = "DT_FINE_VAL", nullable = false)
    @Temporal(TemporalType.TIMESTAMP)
    public Date getDtFineVal() {
        return dtFineVal;
    }

    public void setDtFineVal(Date dtFineVal) {
        this.dtFineVal = dtFineVal;
    }

    @Basic
    @Column(name = "DT_INI_VAL", nullable = false)
    @Temporal(TemporalType.TIMESTAMP)
    public Date getDtIniVal() {
        return dtIniVal;
    }

    public void setDtIniVal(Date dtIniVal) {
        this.dtIniVal = dtIniVal;
    }

    @Id
    // =
    // "SIORG_ENTE_CONVENZ_ORG_IDENTECONVENZORG_GENERATOR",
    // schema =
    // "SACER_IAM",
    // sequenceName =
    // "SORG_ENTE_CONVENZ_ORG",
    // allocationSize = 1)
    // @GeneratedValue(strategy = GenerationType.SEQUENCE, generator =
    // "SIORG_ENTE_CONVENZ_ORG_IDENTECONVENZORG_GENERATOR")
    @Column(name = "ID_ENTE_CONVENZ_ORG")
    @GenericGenerator(name = "SORG_ENTE_CONVENZ_ORG_ID_ENTE_CONVENZ_ORG_GENERATOR", strategy = "it.eng.sequences.hibernate.NonMonotonicSequenceGenerator", parameters = {
            @Parameter(name = SequenceStyleGenerator.SCHEMA, value = "SACER_IAM"),
            @Parameter(name = SequenceStyleGenerator.SEQUENCE_PARAM, value = "SORG_ENTE_CONVENZ_ORG"),
            @Parameter(name = SequenceStyleGenerator.INCREMENT_PARAM, value = "1") })
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "SORG_ENTE_CONVENZ_ORG_ID_ENTE_CONVENZ_ORG_GENERATOR")
    public Long getIdEnteConvenzOrg() {
        return idEnteConvenzOrg;
    }

    public void setIdEnteConvenzOrg(Long idEnteConvenzOrg) {
        this.idEnteConvenzOrg = idEnteConvenzOrg;
    }

    @ManyToOne(fetch = FetchType.LAZY, cascade = CascadeType.MERGE)
    @JoinColumn(name = "ID_ENTE_CONVENZ", nullable = false)
    public SIOrgEnteSiam getSiOrgEnteConvenz() {
        return siOrgEnteConvenz;
    }

    public void setSiOrgEnteConvenz(SIOrgEnteSiam siOrgEnteConvenz) {
        this.siOrgEnteConvenz = siOrgEnteConvenz;
    }

    @ManyToOne(fetch = FetchType.LAZY, cascade = CascadeType.MERGE)
    @JoinColumn(name = "ID_ORGANIZ_IAM", nullable = false)
    public SIUsrOrganizIam getSiUsrOrganizIam() {
        return siUsrOrganizIam;
    }

    public void setSiUsrOrganizIam(SIUsrOrganizIam siUsrOrganizIam) {
        this.siUsrOrganizIam = siUsrOrganizIam;
    }
}
