package it.eng.parer.grantedEntity;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;

import javax.persistence.Basic;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Auto-generated by: org.apache.openjpa.jdbc.meta.ReverseMappingTool$AnnotatedCodeGenerator edited by fioravanti_f
 */
@Entity
@Table(schema = "SACER_IAM", name = "ORG_AMBIENTE_ENTE_CONVENZ")
public class SIOrgAmbienteEnteConvenz implements Serializable {

    private List<SIDecUsoModelloComunic> decUsoModelloComunics = new ArrayList<>();
    private String dsAmbienteEnteConvenz;
    private Long idAmbienteEnteConvenz;
    private String nmAmbienteEnteConvenz;
    private List<SIOrgEnteSiam> orgEnteConvenzs = new ArrayList<>();

    public SIOrgAmbienteEnteConvenz() {/* Hibernate */
    }

    public SIOrgAmbienteEnteConvenz(Long idAmbienteEnteConvenz) {
        this.idAmbienteEnteConvenz = idAmbienteEnteConvenz;
    }

    @OneToMany(mappedBy = "siOrgAmbienteEnteConvenz", cascade = CascadeType.MERGE)
    public List<SIDecUsoModelloComunic> getDecUsoModelloComunics() {
        return decUsoModelloComunics;
    }

    public void setDecUsoModelloComunics(List<SIDecUsoModelloComunic> decUsoModelloComunics) {
        this.decUsoModelloComunics = decUsoModelloComunics;
    }

    @Basic
    @Column(name = "DS_AMBIENTE_ENTE_CONVENZ", nullable = false, length = 254)
    public String getDsAmbienteEnteConvenz() {
        return dsAmbienteEnteConvenz;
    }

    public void setDsAmbienteEnteConvenz(String dsAmbienteEnteConvenz) {
        this.dsAmbienteEnteConvenz = dsAmbienteEnteConvenz;
    }

    @Id
    @Column(name = "ID_AMBIENTE_ENTE_CONVENZ")
    public Long getIdAmbienteEnteConvenz() {
        return idAmbienteEnteConvenz;
    }

    public void setIdAmbienteEnteConvenz(Long idAmbienteEnteConvenz) {
        this.idAmbienteEnteConvenz = idAmbienteEnteConvenz;
    }

    @Basic
    @Column(name = "NM_AMBIENTE_ENTE_CONVENZ", nullable = false, length = 100)
    public String getNmAmbienteEnteConvenz() {
        return nmAmbienteEnteConvenz;
    }

    public void setNmAmbienteEnteConvenz(String nmAmbienteEnteConvenz) {
        this.nmAmbienteEnteConvenz = nmAmbienteEnteConvenz;
    }

    @OneToMany(mappedBy = "siOrgAmbienteEnteConvenz", cascade = CascadeType.MERGE)
    public List<SIOrgEnteSiam> getOrgEnteConvenzs() {
        return orgEnteConvenzs;
    }

    public void setOrgEnteConvenzs(List<SIOrgEnteSiam> orgEnteConvenzs) {
        this.orgEnteConvenzs = orgEnteConvenzs;
    }

}
