package it.eng.parer.grantedEntity;

import java.io.Serializable;
import java.util.*;
import javax.persistence.*;

/**
 * Auto-generated by: org.apache.openjpa.jdbc.meta.ReverseMappingTool$AnnotatedCodeGenerator edited by fioravanti_f
 */
@Entity
@Table(schema = "SACER_IAM", name = "ORG_ENTE_CONVENZ_ORG")
public class SIOrgEnteConvenzOrg implements Serializable {
    private Date dtFineVal;
    private Date dtIniVal;
    private long idEnteConvenzOrg;
    private SIOrgEnteSiam siOrgEnteConvenz;
    private SIUsrOrganizIam siUsrOrganizIam;

    public SIOrgEnteConvenzOrg() {
    }

    public SIOrgEnteConvenzOrg(long idEnteConvenzOrg) {
        this.idEnteConvenzOrg = idEnteConvenzOrg;
    }

    @Basic
    @Column(name = "DT_FINE_VAL", nullable = false)
    @Temporal(TemporalType.TIMESTAMP)
    public Date getDtFineVal() {
        return dtFineVal;
    }

    public void setDtFineVal(Date dtFineVal) {
        this.dtFineVal = dtFineVal;
    }

    @Basic
    @Column(name = "DT_INI_VAL", nullable = false)
    @Temporal(TemporalType.TIMESTAMP)
    public Date getDtIniVal() {
        return dtIniVal;
    }

    public void setDtIniVal(Date dtIniVal) {
        this.dtIniVal = dtIniVal;
    }

    @Id
    @SequenceGenerator(name = "SIORG_ENTE_CONVENZ_ORG_IDENTECONVENZORG_GENERATOR", sequenceName = "SACER_IAM.SORG_ENTE_CONVENZ_ORG", allocationSize = 1)
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "SIORG_ENTE_CONVENZ_ORG_IDENTECONVENZORG_GENERATOR")
    @Column(name = "ID_ENTE_CONVENZ_ORG")
    public long getIdEnteConvenzOrg() {
        return idEnteConvenzOrg;
    }

    public void setIdEnteConvenzOrg(long idEnteConvenzOrg) {
        this.idEnteConvenzOrg = idEnteConvenzOrg;
    }

    @ManyToOne(fetch = FetchType.LAZY, cascade = CascadeType.MERGE)
    @JoinColumn(name = "ID_ENTE_CONVENZ", nullable = false)
    public SIOrgEnteSiam getSiOrgEnteConvenz() {
        return siOrgEnteConvenz;
    }

    public void setSiOrgEnteConvenz(SIOrgEnteSiam siOrgEnteConvenz) {
        this.siOrgEnteConvenz = siOrgEnteConvenz;
    }

    @ManyToOne(fetch = FetchType.LAZY, cascade = CascadeType.MERGE)
    @JoinColumn(name = "ID_ORGANIZ_IAM", nullable = false)
    public SIUsrOrganizIam getSiUsrOrganizIam() {
        return siUsrOrganizIam;
    }

    public void setSiUsrOrganizIam(SIUsrOrganizIam siUsrOrganizIam) {
        this.siUsrOrganizIam = siUsrOrganizIam;
    }
}