package it.eng.parer.grantedEntity;

import java.io.Serializable;
import java.util.*;
import javax.persistence.*;

/**
 * Auto-generated by: org.apache.openjpa.jdbc.meta.ReverseMappingTool$AnnotatedCodeGenerator edited by fioravanti_f
 */
@Entity
@Table(schema = "SACER_IAM", name = "USR_ORGANIZ_IAM")
public class SIUsrOrganizIam implements Serializable {
    private SIAplApplic sIAplApplic;
    private SIAplTipoOrganiz siAplTipoOrganiz;
    private String dsOrganiz;
    private long idOrganizApplic;
    private long idOrganizIam;
    private String nmOrganiz;
    private List<SIOrgEnteConvenzOrg> orgEnteConvenzOrgs;

    private SIUsrOrganizIam siUsrOrganizIam;
    private List<SIUsrOrganizIam> usrOrganizIams;

    public SIUsrOrganizIam() {
    }

    public SIUsrOrganizIam(long idOrganizIam) {
        this.idOrganizIam = idOrganizIam;
    }

    @ManyToOne(fetch = FetchType.LAZY, cascade = CascadeType.MERGE)
    @JoinColumn(name = "ID_APPLIC", nullable = false)
    public SIAplApplic getsIAplApplic() {
        return sIAplApplic;
    }

    public void setsIAplApplic(SIAplApplic sIAplApplic) {
        this.sIAplApplic = sIAplApplic;
    }

    @ManyToOne(fetch = FetchType.LAZY, cascade = CascadeType.MERGE)
    @JoinColumn(name = "ID_TIPO_ORGANIZ", nullable = false)
    public SIAplTipoOrganiz getSiAplTipoOrganiz() {
        return siAplTipoOrganiz;
    }

    public void setSiAplTipoOrganiz(SIAplTipoOrganiz siAplTipoOrganiz) {
        this.siAplTipoOrganiz = siAplTipoOrganiz;
    }

    @Basic
    @Column(name = "DS_ORGANIZ", nullable = false, length = 254)
    public String getDsOrganiz() {
        return dsOrganiz;
    }

    public void setDsOrganiz(String dsOrganiz) {
        this.dsOrganiz = dsOrganiz;
    }

    @Basic
    @Column(name = "ID_ORGANIZ_APPLIC")
    public long getIdOrganizApplic() {
        return idOrganizApplic;
    }

    public void setIdOrganizApplic(long idOrganizApplic) {
        this.idOrganizApplic = idOrganizApplic;
    }

    @Id
    @Column(name = "ID_ORGANIZ_IAM")
    public long getIdOrganizIam() {
        return idOrganizIam;
    }

    public void setIdOrganizIam(long idOrganizIam) {
        this.idOrganizIam = idOrganizIam;
    }

    @Basic
    @Column(name = "NM_ORGANIZ", nullable = false, length = 100)
    public String getNmOrganiz() {
        return nmOrganiz;
    }

    public void setNmOrganiz(String nmOrganiz) {
        this.nmOrganiz = nmOrganiz;
    }

    @OneToMany(mappedBy = "siUsrOrganizIam", cascade = CascadeType.MERGE)
    public List<SIOrgEnteConvenzOrg> getOrgEnteConvenzOrgs() {
        return orgEnteConvenzOrgs;
    }

    public void setOrgEnteConvenzOrgs(List<SIOrgEnteConvenzOrg> orgEnteConvenzOrgs) {
        this.orgEnteConvenzOrgs = orgEnteConvenzOrgs;
    }

    @ManyToOne(fetch = FetchType.LAZY, cascade = CascadeType.MERGE)
    @JoinColumn(name = "ID_ORGANIZ_IAM_PADRE")
    public SIUsrOrganizIam getSiUsrOrganizIam() {
        return siUsrOrganizIam;
    }

    public void setSiUsrOrganizIam(SIUsrOrganizIam siUsrOrganizIam) {
        this.siUsrOrganizIam = siUsrOrganizIam;
    }

    @OneToMany(mappedBy = "siUsrOrganizIam", cascade = CascadeType.MERGE)
    public List<SIUsrOrganizIam> getUsrOrganizIams() {
        return usrOrganizIams;
    }

    public void setUsrOrganizIams(List<SIUsrOrganizIam> usrOrganizIams) {
        this.usrOrganizIams = usrOrganizIams;
    }

}