package it.eng.parer.entity.constraint;

/**
 * ARO_UPD_UNITA_DOC's constraint
 *
 * @author sinatti_s
 */
public final class AroUpdUnitaDoc {

    private AroUpdUnitaDoc() {
    }

    /**
     * Stato UD in conservazione
     * 
     * " ti_stato_udp_elenco_vers IN ('IN_ATTESA_SCHED', 'IN_ELENCO_APERTO', 'IN_ELENCO_CHIUSO', 'IN_ELENCO_COMPLETATO',
     * 'IN_ELENCO_CON_INDICI_AIP_GENERATI', 'IN_ELENCO_DA_CHIUDERE', 'IN_ELENCO_VALIDATO',
     * 'IN_ELENCO_IN_CODA_INDICE_AIP', 'NON_SELEZ_SCHED', 'IN_ELENCO_CON_ELENCO_INDICI_AIP_CREATO',
     * 'IN_ELENCO_CON_ELENCO_INDICI_AIP_ERR_MARCA', 'IN_ELENCO_CON_ELENCO_INDICI_AIP_FIRMATO',
     * 'IN_ELENCO_CON_FIRME_VERIFICATE_DT_VERS', 'IN_CODA_JMS_VERIFICA_FIRME_DT_VERS',
     * 'IN_CODA_JMS_INDICE_AIP_DA_ELAB')"
     */
    public enum AroUpdUDTiStatoUpdElencoVers {
        IN_ATTESA_SCHED, IN_ELENCO_APERTO, IN_ELENCO_CHIUSO, IN_ELENCO_COMPLETATO, IN_ELENCO_CON_INDICI_AIP_GENERATI,
        IN_ELENCO_DA_CHIUDERE, IN_ELENCO_VALIDATO, IN_ELENCO_IN_CODA_INDICE_AIP, NON_SELEZ_SCHED,
        IN_ELENCO_CON_ELENCO_INDICI_AIP_CREATO, IN_ELENCO_CON_ELENCO_INDICI_AIP_ERR_MARCA,
        IN_ELENCO_CON_ELENCO_INDICI_AIP_FIRMATO, IN_ELENCO_CON_FIRME_VERIFICATE_DT_VERS,
        IN_CODA_JMS_VERIFICA_FIRME_DT_VERS, IN_CODA_JMS_INDICE_AIP_DA_ELAB
    }
}