package it.eng.parer.entity.constraint;

/**
 *
 * @author Iacolucci_M
 */
public final class OrgPartition {

    private OrgPartition() {
    }

    public enum TiPartition {
        AIP_UD, BLOB, FILE_SES, SES, UNI_DOC, UNI_DOC_SUB_STRUT, FILE, XML_SES, FASCICOLO, FASCICOLO_ERR, FASCICOLO_KO,
        SES_FASCICOLO_KO, XML_FASCICOLO, XML_VERS_FASCICOLO, XML_SES_FASCICOLO_KO, FILE_META_VER_AIP_FASC,
        FILE_ELENCHI_VERS, FILE_ELENCO_VERS_FASC, FILE_SER, FILE_VOL_SER, VERS_INI_DATI_SPEC, UPD_DATI_SPEC_UNITA_DOC,
        XML_UPD_UNITA_DOC, UPD_UNITA_DOC_KO, SES_UPD_UNITA_DOC_KO, XML_SES_UPD_UNITA_DOC_KO, SES_UPD_UNITA_DOC_ERR
    }

}
